### ISSUE TITLE
Cookie experation type missmatch.

### ISSUE THREAD

**Issue by dcolt** [Codeception/module-phalcon4#18]
Symphonys browser-kit Cookie takes `$expires` as a `string|null`
Phalcon4s cooke typehint is set as `string`, but it's actual return is an int. (Tested with Phalcon 4.1.2)

so in `src/Codeception/Lib/Connector/Phalcon4.php:L152` needs to be casted to a string `(string)$cookie->getExpiration()`

**Comment by Jeckerson** [comment]
@dcolt Hello, could you submit the PR?

**Comment by dcolt** [comment]
Added:  #19
